package models;
// Generated 03-feb-2017 13:59:15 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cines generated by hbm2java
 */
public class Cines implements java.io.Serializable {

	private Integer idCine;
	private String nombre;
	private String cif;
	private Integer telefono;
	private String direccion;
	private Set salases = new HashSet(0);
	private Set empleadoses = new HashSet(0);

	public Cines() {
	}

	public Cines(String nombre, String cif, Integer telefono, String direccion, Set salases, Set empleadoses) {
		this.nombre = nombre;
		this.cif = cif;
		this.telefono = telefono;
		this.direccion = direccion;
		this.salases = salases;
		this.empleadoses = empleadoses;
	}

	public Integer getIdCine() {
		return this.idCine;
	}

	public void setIdCine(Integer idCine) {
		this.idCine = idCine;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set getSalases() {
		return this.salases;
	}

	public void setSalases(Set salases) {
		this.salases = salases;
	}

	public Set getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set empleadoses) {
		this.empleadoses = empleadoses;
	}

}
