package models;
// Generated 03-feb-2017 13:59:15 by Hibernate Tools 4.3.1.Final

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private Integer idEmpleado;
	private Cines cines;
	private String nombre;
	private String apellidos;
	private Integer telefono;
	private String dni;
	private String direccionEmpleado;
	private int accesoUsuario;
	private int accesoContrasenya;
	private Byte tipoEmpleado;

	public Empleados() {
	}

	public Empleados(Cines cines, int accesoUsuario, int accesoContrasenya) {
		this.cines = cines;
		this.accesoUsuario = accesoUsuario;
		this.accesoContrasenya = accesoContrasenya;
	}

	public Empleados(Cines cines, String nombre, String apellidos, Integer telefono, String dni,
			String direccionEmpleado, int accesoUsuario, int accesoContrasenya, Byte tipoEmpleado) {
		this.cines = cines;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.telefono = telefono;
		this.dni = dni;
		this.direccionEmpleado = direccionEmpleado;
		this.accesoUsuario = accesoUsuario;
		this.accesoContrasenya = accesoContrasenya;
		this.tipoEmpleado = tipoEmpleado;
	}

	public Integer getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(Integer idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public Cines getCines() {
		return this.cines;
	}

	public void setCines(Cines cines) {
		this.cines = cines;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getDireccionEmpleado() {
		return this.direccionEmpleado;
	}

	public void setDireccionEmpleado(String direccionEmpleado) {
		this.direccionEmpleado = direccionEmpleado;
	}

	public int getAccesoUsuario() {
		return this.accesoUsuario;
	}

	public void setAccesoUsuario(int accesoUsuario) {
		this.accesoUsuario = accesoUsuario;
	}

	public int getAccesoContrasenya() {
		return this.accesoContrasenya;
	}

	public void setAccesoContrasenya(int accesoContrasenya) {
		this.accesoContrasenya = accesoContrasenya;
	}

	public Byte getTipoEmpleado() {
		return this.tipoEmpleado;
	}

	public void setTipoEmpleado(Byte tipoEmpleado) {
		this.tipoEmpleado = tipoEmpleado;
	}

}
