package models;
// Generated 03-feb-2017 13:59:15 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Peliculas generated by hbm2java
 */
public class Peliculas implements java.io.Serializable {

	private Integer idPelicula;
	private String nombrePelicula;
	private String categoria;
	private String director;
	private Set proyeccions = new HashSet(0);

	public Peliculas() {
	}

	public Peliculas(String nombrePelicula, String categoria, String director, Set proyeccions) {
		this.nombrePelicula = nombrePelicula;
		this.categoria = categoria;
		this.director = director;
		this.proyeccions = proyeccions;
	}

	public Integer getIdPelicula() {
		return this.idPelicula;
	}

	public void setIdPelicula(Integer idPelicula) {
		this.idPelicula = idPelicula;
	}

	public String getNombrePelicula() {
		return this.nombrePelicula;
	}

	public void setNombrePelicula(String nombrePelicula) {
		this.nombrePelicula = nombrePelicula;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public Set getProyeccions() {
		return this.proyeccions;
	}

	public void setProyeccions(Set proyeccions) {
		this.proyeccions = proyeccions;
	}

}
