package models;
// Generated 03-feb-2017 13:59:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Proyeccion generated by hbm2java
 */
public class Proyeccion implements java.io.Serializable {

	private Integer idProyeccion;
	private Peliculas peliculas;
	private Salas salas;
	private Date hora;
	private Date fecha;

	public Proyeccion() {
	}

	public Proyeccion(Peliculas peliculas, Salas salas) {
		this.peliculas = peliculas;
		this.salas = salas;
	}

	public Proyeccion(Peliculas peliculas, Salas salas, Date hora, Date fecha) {
		this.peliculas = peliculas;
		this.salas = salas;
		this.hora = hora;
		this.fecha = fecha;
	}

	public Integer getIdProyeccion() {
		return this.idProyeccion;
	}

	public void setIdProyeccion(Integer idProyeccion) {
		this.idProyeccion = idProyeccion;
	}

	public Peliculas getPeliculas() {
		return this.peliculas;
	}

	public void setPeliculas(Peliculas peliculas) {
		this.peliculas = peliculas;
	}

	public Salas getSalas() {
		return this.salas;
	}

	public void setSalas(Salas salas) {
		this.salas = salas;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
